install:
  - sudo apt-get update
  - sudo apt-get install puppet libxml2-dev libreadline-dev augeas-lenses libaugeas-dev
  - sudo cp -R $TRAVIS_BUILD_DIR/spec/fixtures/augeas/etc/dovecot /etc/
  - sudo cp $TRAVIS_BUILD_DIR/spec/fixtures/augeas/etc/init.d/dovecot /etc/init.d/
  - sudo cp files/* /usr/share/augeas/lenses/dist/
  - sudo mkdir /var/lib/dovecot/
  - sudo groupadd dovecot
language: ruby
bundler_args: --without development
script: "sudo -E bash ./travis_build.sh $PATH"
rvm:
  - 1.8.7
env:
  - PUPPET_GEM_VERSION="~> 2.7.0"
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email: false
